# Generated by Django 3.2.9 on 2024-04-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumermodel',
            name='register_as',
            field=models.CharField(choices=[('consumer', 'CONSUMER'), ('manager', 'MANAGER')], max_length=12, null=True),
        ),
    ]
