# Generated by Django 3.2.9 on 2024-04-16 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0003_consumermodel_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumermodel',
            name='is_verified',
        ),
    ]
